



	INSERT INTO items ( name, description, post_price, end_date, image,condition,poster_email, winner_email) values ()^
	INSERT INTO items ( name, description, post_price, end_date, image,condition,poster_email, winner_email) values ()^
	INSERT INTO items ( name, description, post_price, end_date, image,condition,poster_email, winner_email) values ()^
	INSERT INTO items ( name, description, post_price, end_date, image,condition,poster_email, winner_email) values ()^
	INSERT INTO items ( name, description, post_price, end_date, image,condition,poster_email, winner_email) values ()^
	INSERT INTO items ( name, description, post_price, end_date, image,condition,poster_email, winner_email) values ()^
	INSERT INTO items ( name, description, post_price, end_date, image,condition,poster_email, winner_email) values ()^
	INSERT INTO items ( name, description, post_price, end_date, image,condition,poster_email, winner_email) values ()^
	INSERT INTO items ( name, description, post_price, end_date, image,condition,poster_email, winner_email) values ()^
	INSERT INTO items ( name, description, post_price, end_date, image,condition,poster_email, winner_email) values ()^
	INSERT INTO items ( name, description, post_price, end_date, image,condition,poster_email, winner_email) values ()^
	INSERT INTO items ( name, description, post_price, end_date, image,condition,poster_email, winner_email) values ()^
	INSERT INTO items ( name, description, post_price, end_date, image,condition,poster_email, winner_email) values ()^
	INSERT INTO items ( name, description, post_price, end_date, image,condition,poster_email, winner_email) values ()^
	INSERT INTO items ( name, description, post_price, end_date, image,condition,poster_email, winner_email) values ()^
	INSERT INTO items ( name, description, post_price, end_date, image,condition,poster_email, winner_email) values ()^
	INSERT INTO items ( name, description, post_price, end_date, image,condition,poster_email, winner_email) values ()^
	INSERT INTO items ( name, description, post_price, end_date, image,condition,poster_email, winner_email) values ()^
	INSERT INTO items ( name, description, post_price, end_date, image,condition,poster_email, winner_email) values ()^
	INSERT INTO items ( name, description, post_price, end_date, image,condition,poster_email, winner_email) values ()^
	INSERT INTO items ( name, description, post_price, end_date, image,condition,poster_email, winner_email) values ()^
	INSERT INTO items ( name, description, post_price, end_date, image,condition,poster_email, winner_email) values ()^
	INSERT INTO items ( name, description, post_price, end_date, image,condition,poster_email, winner_email) values ()^
	INSERT INTO items ( name, description, post_price, end_date, image,condition,poster_email, winner_email) values ()^
	INSERT INTO items ( name, description, post_price, end_date, image,condition,poster_email, winner_email) values ()^
	INSERT INTO items ( name, description, post_price, end_date, image,condition,poster_email, winner_email) values ()^
	INSERT INTO items ( name, description, post_price, end_date, image,condition,poster_email, winner_email) values ()^
	INSERT INTO items ( name, description, post_price, end_date, image,condition,poster_email, winner_email) values ()^
	INSERT INTO items ( name, description, post_price, end_date, image,condition,poster_email, winner_email) values ()^
	INSERT INTO items ( name, description, post_price, end_date, image,condition,poster_email, winner_email) values ()^
	INSERT INTO items ( name, description, post_price, end_date, image,condition,poster_email, winner_email) values ()^
	INSERT INTO items ( name, description, post_price, end_date, image,condition,poster_email, winner_email) values ()^
	INSERT INTO items ( name, description, post_price, end_date, image,condition,poster_email, winner_email) values ()^
	INSERT INTO items ( name, description, post_price, end_date, image,condition,poster_email, winner_email) values ()^
	INSERT INTO items ( name, description, post_price, end_date, image,condition,poster_email, winner_email) values ()^
	INSERT INTO items ( name, description, post_price, end_date, image,condition,poster_email, winner_email) values ()^
	INSERT INTO items ( name, description, post_price, end_date, image,condition,poster_email, winner_email) values ()^
	INSERT INTO items ( name, description, post_price, end_date, image,condition,poster_email, winner_email) values ()^
	INSERT INTO items ( name, description, post_price, end_date, image,condition,poster_email, winner_email) values ()^
	INSERT INTO items ( name, description, post_price, end_date, image,condition,poster_email, winner_email) values ()^
	INSERT INTO items ( name, description, post_price, end_date, image,condition,poster_email, winner_email) values ()^
	INSERT INTO items ( name, description, post_price, end_date, image,condition,poster_email, winner_email) values ()^
	INSERT INTO items ( name, description, post_price, end_date, image,condition,poster_email, winner_email) values ()^
	INSERT INTO items ( name, description, post_price, end_date, image,condition,poster_email, winner_email) values ()^
	INSERT INTO items ( name, description, post_price, end_date, image,condition,poster_email, winner_email) values ()^
	INSERT INTO items ( name, description, post_price, end_date, image,condition,poster_email, winner_email) values ()^
	INSERT INTO items ( name, description, post_price, end_date, image,condition,poster_email, winner_email) values ()^
	INSERT INTO items ( name, description, post_price, end_date, image,condition,poster_email, winner_email) values ()^
	INSERT INTO items ( name, description, post_price, end_date, image,condition,poster_email, winner_email) values ()^
	INSERT INTO items ( name, description, post_price, end_date, image,condition,poster_email, winner_email) values ()^
	INSERT INTO items ( name, description, post_price, end_date, image,condition,poster_email, winner_email) values ()^
	INSERT INTO items ( name, description, post_price, end_date, image,condition,poster_email, winner_email) values ()^
	INSERT INTO items ( name, description, post_price, end_date, image,condition,poster_email, winner_email) values ()^
	INSERT INTO items ( name, description, post_price, end_date, image,condition,poster_email, winner_email) values ()^
	INSERT INTO items ( name, description, post_price, end_date, image,condition,poster_email, winner_email) values ()^
	INSERT INTO items ( name, description, post_price, end_date, image,condition,poster_email, winner_email) values ()^
	INSERT INTO items ( name, description, post_price, end_date, image,condition,poster_email, winner_email) values ()^
	INSERT INTO items ( name, description, post_price, end_date, image,condition,poster_email, winner_email) values ()^
	INSERT INTO items ( name, description, post_price, end_date, image,condition,poster_email, winner_email) values ()^
	INSERT INTO items ( name, description, post_price, end_date, image,condition,poster_email, winner_email) values ()^
	INSERT INTO items ( name, description, post_price, end_date, image,condition,poster_email, winner_email) values ()^
	INSERT INTO items ( name, description, post_price, end_date, image,condition,poster_email, winner_email) values ()^
	INSERT INTO items ( name, description, post_price, end_date, image,condition,poster_email, winner_email) values ()^
	INSERT INTO items ( name, description, post_price, end_date, image,condition,poster_email, winner_email) values ()^
	INSERT INTO items ( name, description, post_price, end_date, image,condition,poster_email, winner_email) values ()^
	INSERT INTO items ( name, description, post_price, end_date, image,condition,poster_email, winner_email) values ()^
	INSERT INTO items ( name, description, post_price, end_date, image,condition,poster_email, winner_email) values ()^
	INSERT INTO items ( name, description, post_price, end_date, image,condition,poster_email, winner_email) values ()^
	INSERT INTO items ( name, description, post_price, end_date, image,condition,poster_email, winner_email) values ()^
	INSERT INTO items ( name, description, post_price, end_date, image,condition,poster_email, winner_email) values ()^

